---
- name: nginx restart
  docker_container:
    name: nginx
    restart: yes

- name: apply netplan
  command: netplan apply
  async: 45
  poll: 0

- name: restart resolvconf
  service:
    name: resolvconf
    state: restarted
    
- name: restore iptables
  shell: "iptables-restore < /etc/iptables/rules.v4"

- name: reload haproxy
  service:
    name: haproxy
    state: restarted