---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-server
  template:
    metadata:
      labels:
        app: kafka-server

    spec:
      hostname: kafka-server
      containers:
        image: wurstmeister/kafka
        name: kafka
        imagePullPolicy: IfNotPresent

      - env:
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
<<<<<<< HEAD
          value:  10.101.214.142:2181
=======
          value: 10.101.214.142:2181
>>>>>>> 91d38edc800fe2ae28845195d507879f4b5d90a5
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka:9092
        - name: KAFKA_CREATE_TOPICS
          value: input:1:1,output1:1
        
        ports:
        - containerPort: 9092
        volumeMounts:
            - name: kafka-data
              mountPath: /home/ubuntu/data/kafka/
      volumes:
        - name: kafka-data
          persistentVolumeClaim:
            claimName: pvc-kafka
            
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
  labels:
    app: kafka-service
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
