---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-zookeeper
spec:
  volumeName: pv-zookeeper
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-kafka
spec:
  volumeName: pv-kafka
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
      