---
- name: Iptables Hardening
  import_tasks: iptables.yml
  
- name: Install Requirements
  apt:
    name:
      - resolvconf
    update_cache: yes

- name: Add DNS Addresses
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 8.8.8.8
      nameserver 178.22.122.100
  notify: restart resolvconf
  
- name: Preinstallation
  import_tasks: preinstallation.yml
  
- name: Install dependencies
  import_tasks: kube-dependencies.yml
