---
- name: Remove swapfile from /etc/fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Disable the ufw firewall 
  service:
    name: ufw
    state: stopped
    enabled: false

- name: Set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    reload: yes

- name: Install containerd
  apt:
    name: 
      - containerd
    state: present
    update_cache: true

- name: Create config files for containerd
  file:
    state: file
    path: "/etc/modules-load.d/containerd.conf"
    owner: root
    group: root
    mode: 0755

- name: Add conf for containerd
  blockinfile:
    path: "/etc/modules-load.d/containerd.conf"
    block: |
            overlay
            br_netfilter
  notify: restart containerd

- name: Create containerd config directory
  file:
    state: directory
    path: /etc/containerd 
    owner: root
    group: root
    mode: 0755

- name: Install containerd
  become: yes
  shell: |
          containerd config default | sudo tee /etc/containerd/config.toml

- name: Load bridge network filter and overlay modprobe module
  modprobe:
    name: '{{ item }}'
    state: present
  with_items:
    - br_netfilter
    - overlay

- name: Create config files for K8S networking
  file:
    state: file
    path: "/etc/sysctl.d/kubernetes.conf"
    owner: root
    group: root
    mode: 0755

- name: Add conf for containerd
  blockinfile:
    path: "/etc/sysctl.d/kubernetes.conf"
    block: |
            net.bridge.bridge-nf-call-ip6tables = 1
            net.bridge.bridge-nf-call-iptables = 1
            net.ipv4.ip_forward = 1
  register: result

- name: Apply new settings
  become: yes
  command: sysctl --system
  when: result.changed
