---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-producer
  namespace: kafka
  labels:
    app: kafka-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-producer
  template:
    metadata:
      labels:
        app: kafka-producer
    spec:
      containers:
      - name: kafka-producer
        imagePullPolicy: IfNotPresent
        image: mregistry.bukhara-chkh.ir/producer:v3
      imagePullSecrets:
      - name: docker
