---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - env:
        - name: kafka.server
          value: "kafka:9092"
      - name: kafka-exporter
        imagePullPolicy: IfNotPresent
        image: danielqsj/kafka-exporter:v1.4.2
        ports:
        - name: http-metrics
          containerPort: 9308
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  ports:
  - name: http-metrics
    port: 80
    protocol: TCP
    targetPort: 9308
