---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-ini
  labels:
    app.kubernetes.io/name: grafana-ini
    app.kubernetes.io/component: grafana
data:
  # Grafana's main configuration file.
  grafana.ini: |-
    [analytics]
      check_for_updates = true
    [log]
      mode = console
      level = info
    [paths]
      data = /var/lib/grafana
      logs = /var/log/grafana
      provisioning = /etc/grafana
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    app.kubernetes.io/name: grafana-datasources
data:
  # A file that specifies data sources for Grafana to use to populate dashboards. 
  datasources.yaml: |-
    {
        "apiVersion": 1,
        "datasources": [
            {
                "access": "proxy",
                "editable": false,
                "name": "prometheus",
                "orgId": 1,
                "type": "prometheus",
                "url": "http://prometheus.prometheus.svc:9090",
                "basicAuth": true,
                "basicAuthUser": "admin",
                "secureJsonData": {
                  "basicAuthPassword": "password"
                },
                "isDefault": "true"
            }
        ]
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboard-providers
  labels:
    app.kubernetes.io/name: grafana-dashboard-providers
data:
  # A file that configures where Grafana should look for dashboards to load when starting up. 
  # By default, the `dashboards-configmap.yaml` ConfigMap will be mounted to `/var/lib/grafana/dashboards` which is referenced in this file.
  dashboardproviders.yaml: |-
    apiVersion: 1
    providers:
    - disableDeletion: false
      editable: true
      folder: ""
      name: default
      options:
        path: /var/lib/grafana/dashboards
      orgId: 1
      type: file
