---
- name: Netplan congifuration
  import_tasks: netplan.yml

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: Join workers to kubernetes cluster
  import_tasks: kubeadm-worker-join.yml