---
- name: Install Requirements
  apt:
    name:
      - resolvconf
    update_cache: yes

- name: Add DNS Addresses
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 8.8.8.8
      nameserver 178.22.122.100
  notify: restart resolvconf

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: Copy hosts file
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: 0644
