---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc-kafka
spec:
  volumeName: task-pv-kafka
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi