---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: task-pvc-zookeeper
spec:
  volumeName: task-pv-zookeeper
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi