---
- name: Netplan congifuration
  import_tasks: netplan.yml

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: Join masters to kubernetes cluster
  import_tasks: kubeadm-master-join.yml