---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-auth
  labels:
    app.kubernetes.io/name: grafana-auth
    app.kubernetes.io/component: grafana
type: Opaque
data:
  admin-user: YWRtaW4=
  admin-password: YWRtaW4=