---
work_dir: webserver

domain_name: "{{ bukhara_domain_name }}"

kubernetes_addr: "http://{{ master02_ip }}:32323/"
grafana_addr: "http://{{ master02_ip }}:3000/"
prometheus_addr: "http://{{ master02_ip }}:9090/"