---
- name: Get the token for joining the worker nodes
  become: true
  become_user: ubuntu
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: Show debug
  debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  become: true
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="/tmp/kubernetes_join_command" mode=0777