---
- name: Install Requirements
  apt:
    name:
      - resolvconf
    update_cache: yes

- name: Add DNS Addresses
  blockinfile:
    path: /etc/resolvconf/resolv.conf.d/head
    block: |
      nameserver 8.8.8.8
      nameserver 4.2.2.4
      nameserver 178.22.122.100
  notify: restart resolvconf

- name: Iptables Hardening
  import_tasks: iptables.yml

- name: netplan apply
  import_tasks: netplan.yml

- name: Set ip_forward
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes
    reload: yes

- name: Copy hosts file
  template:
    src: hosts/hosts.j2
    dest: /etc/hosts
